import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import { Buffer } from "buffer";
import type { Contador } from "../target/types/contador"; // generated by anchor build

async function main() {
    console.log("Script started...");
  // ── setup ──────────────────────────────────────────────────────────────────

  // Connect to devnet
  const connection = new anchor.web3.Connection(
    anchor.web3.clusterApiUrl("devnet"),
    "confirmed"
  );

  // Load your local wallet (the same one you deployed with)
  const wallet = anchor.Wallet.local();
  console.log("Wallet:", wallet.publicKey.toString());

  const provider = new anchor.AnchorProvider(connection, wallet, {
    commitment: "confirmed",
  });
  anchor.setProvider(provider);

  // Load the program using the IDL generated by anchor build
  const program = anchor.workspace.Contador as Program<Contador>;
  console.log("Program ID:", program.programId.toString());

  // ── derive the counter PDA ─────────────────────────────────────────────────

  const COUNTER_SEED = Buffer.from("counter"); // must match your Rust constant
  const [counterPda] = anchor.web3.PublicKey.findProgramAddressSync(
    [COUNTER_SEED],
    program.programId
  );
  console.log("Counter PDA:", counterPda.toString());

  // ── initialize ─────────────────────────────────────────────────────────────

  console.log("\nInitializing counter...");
  const initTx = await program.methods
    .initialize()
    .accounts({ 
      payer: wallet.publicKey,
      counter: counterPda,
      systemProgram: anchor.web3.SystemProgram.programId,
    })
    .rpc();
  console.log("Init tx:", initTx);

  // ── read state ─────────────────────────────────────────────────────────────

  let state = await program.account.counter.fetch(counterPda);
  console.log("Count after init:", state.count.toString());

  // ── increment (x2) ────────────────────────────────────────────────────────

  console.log("\nIncrementing (1/2)...");
  const inc1Tx = await program.methods
    .increment()
    .accounts({ 
      counter: counterPda,
      authority: wallet.publicKey 
    })
    .rpc();
  console.log("Inc 1 tx:", inc1Tx);

  console.log("Incrementing (2/2)...");
  const inc2Tx = await program.methods
    .increment()
    .accounts({ 
      counter: counterPda,
      authority: wallet.publicKey 
    })
    .rpc();
  console.log("Inc 2 tx:", inc2Tx);

  // ── final state ────────────────────────────────────────────────────────────

  state = await program.account.counter.fetch(counterPda);
  console.log("\nFinal count:", state.count.toString()); // should be 2
  console.log("Authority:  ", state.authority.toString());
}

main().catch(console.error);